using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class enemy_spawn : MonoBehaviour
{
	public GameObject enemys;		//ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Gï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
	public float appearNextTime;  //ï¿½Gï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚Å‚ÌŽï¿½ï¿½ï¿½
	private float elapsedTime;				//ï¿½Ò‚ï¿½ï¿½ï¿½ï¿½ï¿½

	// Use this for initialization
	void Start()
	{
		elapsedTime = 0f;
	}

	void Update()
	{
		//ï¿½@ï¿½oï¿½ßŽï¿½ï¿½Ô‚ð‘«‚ï¿½
		elapsedTime += Time.deltaTime;

		//ï¿½@ï¿½oï¿½ßŽï¿½ï¿½Ô‚ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		if (elapsedTime > appearNextTime)
		{
			elapsedTime = 0f;
			Instantiate(enemys, transform.position, transform.rotation);
		}
	}
}